version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "eztrialpg"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eztrialdb
      - POSTGRES_USER=eztrial
      - POSTGRES_PASSWORD=eztrial123
volumes:
  my_dbdata:
